spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/book_store?createDatabaseIfNotExist=true&Unicode=true&serverTimezone=UTC
    username: root
    password: admin
    #driver-class-name: com.mysql.jdbc.Driver
  # Show SQL logs
  jpa:
    show-sql: true
    ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080
  servlet:
    content-path: /store

jwt:
  secret: ${JWT_SECRET:jwt_some_secret}